name: attendance_manager
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth:
  cloud_firestore:
  google_sign_in: ^4.4.4
  firebase_core: ^0.4.0+9
  firebase_database: ^3.1.5
  http: ^0.12.0+2
  cupertino_icons: ^0.1.3
  flutter_launcher_icons:

dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/attendance.png"
  image_path_android: "assets/attendance.png"

flutter:
  uses-material-design: true
  assets:
    - assets/